version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    groups:
      production-patch-and-minor:
        dependency-type: production
        update-types:
          - patch
          - minor
      development-patch-and-minor:
        dependency-type: development
        update-types:
          - patch
          - minor
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "chore(deps)"
